
# test globe

```{js}
let lastClick = 0;
const ele = document.querySelector('.carousel');
ele.addEventListener('touchstart', function(e) {
  e.preventDefault(); // to disable browser default zoom on double tap
  let date = new Date();
  let time = date.getTime();
  const time_between_taps = 200; // 200ms
  if (time - lastClick < time_between_taps) {
    // do stuff
    countryName = $(".carousel-item.active")[0].ariaLabel;
    lat=capitalDict[countryName][2];
    lon=capitalDict[countryName][3];
    targetTree(lat, lon);
    console.log("done");
  }
  lastClick = time;
})
```


```{r}
plot_capitalTrees() |> 
  app$update()
  econIDV::showWidget()
  econIDV::get_traceInfo() |> View()
```


```{r}
require(htmltools)
require(reactR)
devtools::load_all(".")

carouselPage() |> 
  tagList(
    htmltools::includeScript("./inst/app/js/sidenavcontrol.js")
  ) |>
  app$update()
  # econWeb::browseTag2()
```

```{js}
currentCountry = 
$("#greetingGallery > .carousel-item.active")[0].ariaLabel
console.log(currentCountry)
```


```{r}
require(htmltools)
tag_carousel = function(){
  require(htmltools)
  tags$div(
    class="carousel",
    id="greetingGallery"
  )
}
econWeb::Dependency() -> dep
tag_carousel() |>
  tagList(
    dep$jquery$onCloud(),
    dep$materialise$onCloud(),
    # reactR::html_dependency_react(),
    htmltools::includeScript(
      "inst/app/js/formProcessing.js"
    )
  ) |>
  attachAppDependencies() |>
  save_html(
    "docs/carousel.html"
  )
  app$update()
```

## joinIcon


```{js}
$("#switchGlobe").click(function(){
  console.log("switch")
  $("#globeplace").toggleClass("back");
})

```


```{js}
function elementsOverlap(el1, el2) {
  const domRect1 = el1.getBoundingClientRect();
  const domRect2 = el2.getBoundingClientRect();

  return !(
    domRect1.top > domRect2.bottom ||
    domRect1.right < domRect2.left ||
    domRect1.bottom < domRect2.top ||
    domRect1.left > domRect2.right
  );
}
function isGlobeOverlapWish(){
  let result = elementsOverlap($("#greetingGallery")[0],$("#globeplace")[0])
  console.log(result);
  return result;
}
```

```{r}

list(
    projection = list(
      type ='orthographic',#   'natural earth',
      rotation = list(
        lon=0,
        lat=0,
        roll=0
      )
    ),
    showland = TRUE,
    showocean= TRUE,
    oceancolor="#e3f2fd",
    bgcolor= "#00000000",
    landcolor = "#fff8e1"
  ) |> jsonlite::toJSON() |>
  clipr::write_clip()
```

```{js}
$("#sidenav-play").click(function(){
  tintId=setInterval(function(){greetingGallery.next()},2000);
  $("#sidenav-play").toggle();
  $("#sidenav-stop").toggle();
})
$("#sidenav-stop").click(function(){
  clearInterval(tintId);
  $("#sidenav-play").toggle();
  $("#sidenav-stop").toggle();
})
```

```{r}
fig |> 
  plotly::style(
  
      opacity=0.3
    
  )
```



```{js}
sizeRange=[150, 200, 230, 264, 300, 320, 350];
currentSize=3;
zoomIn = function(){
  if(currentSize >= 6) return;
  currentSize +=1;
  resize_globe(sizeRange[currentSize]);
}
zoomOut = function(){
  if(currentSize<=0) return;
  currentSize -=1;
  resize_globe(sizeRange[currentSize]);
}
resize_globe = function(size){
  //$("#globeplace").toggle();
//setTimeout(function(){
$("#globeplace").width(size+50);
  $("#globeplace").height(size+50);
  Plotly.relayout(
  widget, 
  {width: size, height: size });

  setTimeout(
  function(){
  Plotly.relayout(
  widget,{geo: {projection: {type: "orthographic"},
  showland: true, showocean: true, oceancolor: "#e3f2fd", bgcolor:"#00000000", landcolor:"#fff8e1"}}
)
}, 200
)
//$("#globeplace").toggle();
  
}

$("#zoom-in").click(zoomIn);
$("#zoom-out").click(zoomOut);

```

