---
title: "Untitled"
author: "林茂廷"
date: '2022-06-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## apptest

```{r}
apptest::apptest(port=4321) -> app
```


## 卡片

```{r}
wishCard() |> attachAppDependencies() |> econWeb::browseTag2()
```

## Form to Google Form

https://medium.com/@shashikg.iitk/how-to-create-custom-html-forms-and-submit-responses-to-google-sheet-834d7b3a13b0

https://medium.com/front-end-augustus-study-notes/custom-google-form-en-f7be4c27a98b

https://www.letswrite.tw/custom-google-form/

```{r}
devtools::load_all(".")

load_appmeta() -> appmeta
appmeta$load$googleForm()
ids = c("inputName", "inputId","inputBday", "inputWords") 
wishCard(ids=ids, googleForm)

wishCard(
  ids = generate_ids(),
  googleForm=generate_googleForm()) |>
  econWeb::browseTag2()
``` 

```{r}
dir.create("docs")
appDep() |> 
  htmltools::save_html("docs/index.html")
```



### Form

  * <https://github.com/levinunnink/html-form-to-google-sheet>

```{r}
form(.names=c("name","schoolId", "bday", "words"),
  postUrl="https://script.google.com/macros/s/AKfycbzOL5ZUBa2QUtCwM-jMJ0x-KpeR0baxkLy90pLjSCN74BwzcxvgsdNfrprEBd3Zk_Jrew/exec") |> 
  attachAppDependencies() |> app$update()
```


https://script.google.com/macros/s/AKfycbzOL5ZUBa2QUtCwM-jMJ0x-KpeR0baxkLy90pLjSCN74BwzcxvgsdNfrprEBd3Zk_Jrew/exec

https://docs.google.com/spreadsheets/d/1AE7_zIHORciJF3QmFaQrWeq4c9gmhzyycOYO1FblRbk/edit#gid=0


```{r}
wishCard(
  ids = generate_ids(),
  .names=c("name","schoolId", "bday", "words"),
  postUrl="https://script.google.com/macros/s/AKfycbzOL5ZUBa2QUtCwM-jMJ0x-KpeR0baxkLy90pLjSCN74BwzcxvgsdNfrprEBd3Zk_Jrew/exec") |> app$update()
```

## Globe card

```{r}
globeCard() |> 
  attachAppDependencies() |> 
  htmltools::save_html("docs/index.html")
  app$update()
```

```{r}
globeCard() |>
  attachAppDependencies() |> app$update()
```


### restyle

#### Only Taipei visible

```{js}
var clearTree = {
    visible: false
};

clearTrees = function(){
  let nonTaiwanTraces = Array.from({length: 244}, (_, i) => i + 1)
  Plotly.restyle(widget, clearTree, nonTaiwanTraces);
  treesPlanted =1;
}

var plantTree = {
   visible: true
}
treesPlanted = 1;
plantOneMoreTree = function(){
  Plotly.restyle(widget, plantTree, treesPlanted)
  treesPlanted = treesPlanted+1
}
```


```{r}
whichIsTaipei = which(capitals$CapitalName=="Taipei")
rbind(capitals[whichIsTaipei,], capitals[-whichIsTaipei,]) -> capitals

plot_capitalTrees() |> 
  plotly::plotly_build() -> p
View(p)
```

```{r}
plot_capitalTrees() |>
  plotly::style(
    visible=F
  ) -> p1 
p1
p1 |> 
  plotly::style(
    visible=T,
    traces=1
  )

```

```{r}
plot_capitalTrees() |>
  htmlwidgets::onRender("function(e){widget=e;}") |> 
  attachAppDependencies() |> app$update()
```

```{js}
$gframe = $("#myframe");
console.log($gframe);
```

###

Web app Url
```{r}
webAppUrl = "https://script.google.com/macros/s/AKfycbzwvtI0uutxZT15CSnoCNPLHDcChgd-2vHLInsL9jzJa0ioKyu-BJJwo2WTfzG8xFlo3w/exec"
deploymentId="AKfycbzwvtI0uutxZT15CSnoCNPLHDcChgd-2vHLInsL9jzJa0ioKyu-BJJwo2WTfzG8xFlo3w"
```

```{js}

```

### data emit

```{r}
globeCard() |>
  attachAppDependencies() |> app$update()
```

```{d3 data=}
widget.on("plotly_click", function(e){eda_click=e;
countryname = eda_click.points[0].data.name;
console.log(countryname);});
```

